version: '3.8'

services:
  api:
    build: .
    ports:
      - "8001:8001"
    environment:
      - APP_ID=${APP_ID}
      - API_KEY=${API_KEY}
    volumes:
      - ./app:/app/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/docs"]
      interval: 30s
      timeout: 10s
      retries: 3 